# general settings
name: FFNetSR_light_DIV2K
model_type: ESRModel
scale: 2
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: ...  # Change to your own path
    dataroot_lq: ...  # Change to your own path
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192  # input: 192/2
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: ...  # Change to your own path
    dataroot_lq: ...  # Change to your own path
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: FFNetSR
  dim: 96
  depth: 36
  expansion_ratio: 2
  scale: 2
  norm: null

# path
path:
  pretrain_network_g: ~
  strict_load_g: true

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.02
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29506
